### ISSUE TITLE
Factoring title matching

### ISSUE THREAD

**Issue by KittyGiraudel** [tomhodgins/todoml#1]
Hey Tom!

That’s an awesome little project, I love it. I was checking if we could be a little less verbose regarding matching titles. Here is what I came up with:

```js
const titleMatch = line.match(/^(#+) /)
const tagName = titleMatch && ('h' + titleMatch[1].length)

tagName
&& (todoDoc += '<' + tagName + '>' + line.replace(/^#+ /, '') + '</' + tagName + '>')
```

What do you think? :)

**Comment by tomhodgins** [comment]
That's a fantastic idea! Thanks for the suggestion 😍

**Comment by tomhodgins** [comment]
Thanks for commenting and suggesting some code - I've just updated it with almost identical code: https://github.com/tomhodgins/todoml/commit/ca61d00b982a03c134b61c32a50f3da2b36957d7

Yesterday was my first day trying out TodoML, and I'm planning to use it again today, so thanks for making it a little cleaner :)
